version: "3.8"

volumes:
  mongodb_data_container: {}
  grafana_data: {}
  prometheus_data: {}

services:
  app:
    build:
      context: ./
      target: exec
    image: cj:latest
    ports:
      - 8080:8080
    volumes:
      - ./var/www/images:/opt/pics:rw
      - ./var/www/files:/opt/files:rw
    env_file:
      - resources/config/.env
    depends_on:
      - mongodb_container
      - auth_microservice

  auth_microservice:
    build:
      context: ./
      target: exec_auth
    container_name: cj_auth
    ports:
      - 3000:3000
    env_file:
      - resources/config/.env
    depends_on:
      - mongodb_container

  mongodb_container:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db:rw

  adminer:
    image: mongo-express:latest
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: rootpassword
      ME_CONFIG_MONGODB_SERVER: mongodb_container
    ports:
      - 18081:8081
    depends_on:
      - mongodb_container

  webp:
    image: webpsh/webp-server-go
    restart: unless-stopped
    volumes:
      - ./var/www/images:/opt/pics:rw
      - ./var/www/cache:/opt/exhaust:rw
    ports:
      - 3333:3333
    deploy:
      resources:
        limits:
          memory: 200M

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus:/etc/config
    command:
      - '--config.file=/etc/config/prometheus.yml'

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - ./monitoring:/etc/config

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./monitoring:/etc/config
      - grafana_data:/var/lib/grafana

networks:
  default:
    name: api
    external: true
