version: "3.8"
services:
  app:
    build:
      context: ./
      target: exec
    image: cj:latest
    ports:
      - 8080:8080
    volumes:
      - ./var/www/images:/opt/pics
    env_file:
      - resources/config/.env
    depends_on:
      - mongodb_container
      - auth_microservice

  auth_microservice:
    build:
      context: ./
      target: exec_auth
    container_name: cj_auth
    ports:
      - 3000:3000
    env_file:
      - resources/config/.env
    depends_on:
      - mongodb_container

  mongodb_container:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  adminer:
    image: mongo-express:latest
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_SERVER: mongodb_container
    ports:
      - 18081:8081
    depends_on:
      - mongodb_container

  webp:
    image: webpsh/webp-server-go
    restart: unless-stopped
    volumes:
      - ./var/www/images:/opt/pics
      - ./var/www/cache:/opt/exhaust
    ports:
      - 3333:3333
    deploy:
      resources:
        limits:
          memory: 200M

networks:
  default:
    name: api
    external: true

volumes:
  mongodb_data_container:
