global:
  scrape_interval:     120s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "server"
    scrape_interval: 10s
    static_configs:
      - targets: [app:8080]
  - job_name: "auth"
    scrape_interval: 10s
    static_configs:
      - targets: [ auth_microservice:3001 ]
  - job_name: "node exporter"
    scrape_interval: 15s
    static_configs:
      - targets: [ 'node-exporter:9100' ]



#rule_files:
#  - 'alerts.yml'