global:
  scrape_interval:     120s
  evaluation_interval: 10s

scrape_configs:
  - job_name: golang
    scrape_interval:     10s
    static_configs:
      - targets: [app:8080]



rule_files:
#  - 'alerts.yml'

