openapi: 3.0.3
info:
  title: CJ
  description: "Social Network VK"
  version: 0.0.1
servers:
  - url: /api
security:
  - CookieAuth: []

paths:
  /auth/signup:
    get:
      tags:
        - Authorization
      summary: Signup user
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupUserRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignupUserResponse"

  /auth/login:
    get:
      tags:
        - Authorization
      summary: Login user
      security: []
      parameters:
        - $ref: "#/components/parameters/DefaultParameters"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUserRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginUserResponse"

  /auth/logout:
    delete:
      tags:
        - Authorization
      summary: Logout user
      security: []
      parameters:
        - $ref: "#/components/parameters/DefaultParameters"
      responses:
        "500":
          description: Internal error
          content: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicResponse"

  /user/:user_id:
    get:
      tags:
        - User
      summary: Get user data
      security: []
      parameters:
        - $ref: "#/components/parameters/DefaultParameters"
      requestBody:
        description: On empty user_id returns information about currently authorized user if there's one
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetUserDataRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetUserDataResponse"

  /user/user_id/posts:
    get:
      tags:
        - User
      summary: Get user feed
      parameters:
        - $ref: "#/components/parameters/DefaultParameters"
      requestBody:
        description: On empty user_id returns information about currently authorized user if there's one
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetUserFeedRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetUserFeedResponse"
  /post/create:
    post:
      tags:
        - Post
      summary: Create new post
      parameters:
        - $ref: "#/components/parameters/DefaultParameters"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetPostDataRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPostDataResponse"
  /post/delete/:post_id:
    delete:
      tags:
        - Post
      summary: Delete post
      parameters:
        - $ref: "#/components/parameters/DefaultParameters"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetPostDeleteRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasicResponse"
  /post/edit/:post_id:
    put:
      tags:
        - Post
      summary: Edit post
      parameters:
        - $ref: "#/components/parameters/DefaultParameters"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetPostEditRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPostDataResponse"
  /post/:post_id:
    get:
      tags:
        - Post
      summary: Get post
      parameters:
        - $ref: "#/components/parameters/DefaultParameters"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetPostRequest"
        required: true
      responses:
        "500":
          description: Internal error
          content: {}
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPostDataResponse"
components:
  parameters:
    DefaultParameters:
      in: header
      name: X-Request-ID
      schema:
        type: string
        format: uuid

  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: AuthToken

  schemas:
    UserName:
      type: object
      properties:
        first:
          type: string
          example: John
        last:
          type: string
          example: Doe

    GetPostDataRequest:
      type: object
      properties:
        message:
          type: string
          example: This is my new post
        images:
          type: array
          items:
            type: string
            example: src/image.jpg

    GetPostEditRequest:
      type: object
      properties:
        message:
          type: string
          example: This is my new post
        images:
          type: array
          items:
            type: string
            example: src/image.jpg

    GetPostDeleteRequest:
      type: object

    GetPostRequest:
      type: object


    SignupUserRequest:
      type: object
      properties:
        name:
          $ref: "#/components/schemas/UserName"
        email:
          type: string
          example: mail@example.com
        password:
          type: string
          example: password

    GetPostDataResponse:
      $ref: "#/components/schemas/Post"

    SignupUserResponse:
      $ref: "#/components/schemas/BasicResponse"

    LoginUserRequest:
      type: object
      properties:
        email:
          type: string
          example: mail@example.com
        password:
          type: string
          example: password

    LoginUserResponse:
      $ref: "#/components/schemas/BasicResponse"

    GetUserDataRequest:
      type: object


    GetUserDataResponse:
      $ref: "#/components/schemas/User"

    GetUserFeedRequest:
      type: object


    GetUserFeedResponse:
      type: object
      properties:
        posts:
          type: array
          items:
            $ref: "#/components/schemas/Post"

    BasicResponse:
      type: object

    User:
      type: object
      properties:
        id:
          type: string
        name:
          $ref: "#/components/schemas/UserName"
        email:
          type: string
          example: mail@example.com

    Post:
      type: object
      properties:
        author_id:
          type: string
        post_id:
          type: string
        message:
          type: string
        images:
          type: array
          items:
            type: string
