name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev
      - checkCI

jobs:
  tests:
    name: Tests check
    runs-on: ubuntu-latest
    steps:
      - name: Installation Go v1.18
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start tests
        run: |
          make mock
          make tests

  linter:
    name: Linter check
    runs-on: ubuntu-latest
    steps:
      - name: Installation Go v1.18
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2
          $(go env GOPATH)/bin/golangci-lint run

  build:
    needs: [ linter, tests ]
    name: Run Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Shutdown process
        run: make down
      - name: Build
        run: make build

#  deploy:
#    needs: [ build ]
#    name: Backend deploy
#    runs-on: ubuntu-latest
#    steps:

