name: CI

on:
  push:
    branches:
      - dev
      - checkCI
  pull_request:
    branches:
      - main
      - dev
      - checkCI

jobs:
  linter:
    name: Linter check
    runs-on: ubuntu-latest
    steps:
      - name: Installation Go v1.18
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        run: make lint

  deploy:
    needs: [ linter ]
    name: Run Docker
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Docker
        run: make